version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://john.db.elephantsql.com/letmflyp
      SPRING_DATASOURCE_USERNAME: letmflyp
      SPRING_DATASOURCE_PASSWORD: C5iKam6DSMchbfMjcFusvPfh6geO73Hi
